const MediaData = [
  {
    name: 'slide1.mp4',
    description: 'Image a diverse range of resources at different depths',
    location: 'our solution',
    link: '',
    category: 'slides',
    tag: '',
    active: true,
  },
  {
    name: 'slide2.mp4',
    description: 'Shorten exploration surveys from months to weeks',
    location: 'our solution',
    link: '',
    category: 'slides',
    tag: '',
    active: true,
  },
  {
    name: 'slide3.mp4',
    description: 'Improve confidence levels via continous sampling',
    location: 'our solution',
    link: '',
    category: 'slides',
    tag: '',
    active: true,
  },
  {
    name: 'at-atomionic.mp4',
    description: '',
    location: 'careers',
    link: '',
    category: 'main',
    tag: '',
    active: true,
  },
  {
    name: 'career-cover.jpg',
    description: "Answering humanity's energy needs using quantum sensors",
    location: 'careers',
    link: '',
    category: 'teams',
    tag: '',
    active: true,
  },
  {
    name: 'about1.png',
    description: 'Resource exploration',
    location: 'about us',
    link: '',
    category: 'cover',
    tag: '',
    active: true,
  },
  {
    name: 'about2.png',
    description: 'Volcanic eruption detection',
    location: 'about us',
    link: '',
    category: 'cover',
    tag: '',
    active: true,
  },
  {
    name: 'about3.png',
    description: 'Underground mapping',
    location: 'about us',
    link: '',
    category: 'cover',
    tag: '',
    active: true,
  },
  {
    name: 'about4.png',
    description: 'Positioning & navigation',
    location: 'about us',
    link: '',
    category: 'cover',
    tag: '',
    active: true,
  },
  {
    name: 'linkedin.png',
    description: 'linkedin',
    location: 'about us',
    link: 'https://www.linkedin.com/company/atomionics/',
    category: 'social media',
    tag: '',
    active: true,
  },
  {
    name: 'twitter.png',
    description: 'twitter',
    location: 'about us',
    link: 'https://twitter.com/atomionics',
    category: 'social media',
    tag: '',
    active: true,
  },
  {
    name: 'instagram.png',
    description: 'instagram',
    location: 'about us',
    link: 'https://www.instagram.com/atomionics',
    category: 'social media',
    tag: '',
    active: true,
  },
  {
    name: 'linkedin-mobile.png',
    description: 'linkedin mobile',
    location: 'about us',
    link: 'https://www.linkedin.com/company/atomionics/',
    category: 'social media',
    tag: 'mobile',
    active: true,
  },
  {
    name: 'twitter-mobile.png',
    description: 'twitter mobile',
    location: 'about us',
    link: 'https://twitter.com/atomionics',
    category: 'social media',
    tag: 'mobile',
    active: true,
  },
  {
    name: 'instagram-mobile.png',
    description: 'instagram mobile',
    location: 'about us',
    link: 'https://www.instagram.com/atomionics',
    category: 'social media',
    tag: 'mobile',
    active: true,
  },

  {
    name: 'investor1.png',
    description: '',
    location: 'home',
    link: 'https://www.capvista.com.sg/',
    category: 'investor',
    tag: '',
    active: true,
  },
  {
    name: 'investor2.png',
    description: '',
    location: 'home',
    link: 'https://www.joinef.com/',
    category: 'investor',
    tag: '',
    active: true,
  },
  {
    name: 'investor3.png',
    description: '',
    location: 'home',
    link: 'https://sea.500.co/',
    category: 'investor',
    tag: '',
    active: true,
  },
  {
    name: 'investor4.png',
    description: '',
    location: 'home',
    link: 'https://www.sginnovate.com/',
    category: 'investor',
    tag: '',
    active: true,
  },
  {
    name: 'investor5.png',
    description: '',
    location: 'home',
    link: 'https://wavemaker.vc/',
    category: 'investor',
    tag: '',
    active: true,
  },
  {
    name: 'investor6.png',
    description: '',
    location: 'home',
    link: 'https://paspalis.com.au/',
    category: 'investor',
    tag: '',
    active: true,
  },
]

export default MediaData
